//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("UmamusumeAss")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.2.2.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.2.2+4744bd8ca45ee836a4bb5c89e72a29725d93b375")]
[assembly: System.Reflection.AssemblyProductAttribute("UmamusumeAss")]
[assembly: System.Reflection.AssemblyTitleAttribute("UmamusumeAss")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.2.2.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows10.0.17763.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows10.0.17763.0")]

// Generated by the MSBuild WriteCodeFragment class.

