#pragma checksum "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B51F5BF0A9AF59A4E9DBEEB02B19F279059B9CAF"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using UmamusumeWpfGui.Converters;
using Wpf.Ui;
using Wpf.Ui.Controls;
using Wpf.Ui.Converters;
using Wpf.Ui.Markup;


namespace UmamusumeWpfGui.Views {
    
    
    /// <summary>
    /// DeveloperToolsView
    /// </summary>
    public partial class DeveloperToolsView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 66 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CapturePreviewSurface;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CapturePreviewPanContent;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform CapturePreviewTranslateTransform;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CapturePreviewContent;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform CapturePreviewScaleTransform;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas CaptureCropVisualOverlay;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle CaptureCropRectangle;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas CaptureCropOverlay;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle CaptureSelectionRectangle;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CaptureCoordinateBadge;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CaptureCoordinateText;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CaptureRoiBadge;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CaptureRoiText;
        
        #line default
        #line hidden
        
        
        #line 255 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PreviewSurface;
        
        #line default
        #line hidden
        
        
        #line 261 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PreviewPanContent;
        
        #line default
        #line hidden
        
        
        #line 263 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform PreviewTranslateTransform;
        
        #line default
        #line hidden
        
        
        #line 265 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PreviewContent;
        
        #line default
        #line hidden
        
        
        #line 268 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.ScaleTransform PreviewScaleTransform;
        
        #line default
        #line hidden
        
        
        #line 275 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas CropVisualOverlay;
        
        #line default
        #line hidden
        
        
        #line 277 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle CropRectangle;
        
        #line default
        #line hidden
        
        
        #line 285 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas CropOverlay;
        
        #line default
        #line hidden
        
        
        #line 294 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle SelectionRectangle;
        
        #line default
        #line hidden
        
        
        #line 300 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle ImageMatchBestRectangle;
        
        #line default
        #line hidden
        
        
        #line 307 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PreviewCoordinateBadge;
        
        #line default
        #line hidden
        
        
        #line 316 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PreviewCoordinateText;
        
        #line default
        #line hidden
        
        
        #line 319 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PreviewRoiBadge;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PreviewRoiText;
        
        #line default
        #line hidden
        
        
        #line 334 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PreviewMatchBadge;
        
        #line default
        #line hidden
        
        
        #line 345 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PreviewMatchText;
        
        #line default
        #line hidden
        
        
        #line 349 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel EmptyPreview;
        
        #line default
        #line hidden
        
        
        #line 976 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PipelineRoiSurface;
        
        #line default
        #line hidden
        
        
        #line 981 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas PipelineRoiOverlay;
        
        #line default
        #line hidden
        
        
        #line 987 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle PipelineSelectionRectangle;
        
        #line default
        #line hidden
        
        
        #line 993 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle PipelineRoiRectangle;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/UmamusumeAss;V0.2.2.0;component/views/developertoolsview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 7 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            ((UmamusumeWpfGui.Views.DeveloperToolsView)(target)).Loaded += new System.Windows.RoutedEventHandler(this.OnLoaded);
            
            #line default
            #line hidden
            
            #line 8 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            ((UmamusumeWpfGui.Views.DeveloperToolsView)(target)).Unloaded += new System.Windows.RoutedEventHandler(this.OnUnloaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CapturePreviewSurface = ((System.Windows.Controls.Grid)(target));
            
            #line 71 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CapturePreviewSurface.SizeChanged += new System.Windows.SizeChangedEventHandler(this.OnCapturePreviewSurfaceSizeChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.CapturePreviewPanContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.CapturePreviewTranslateTransform = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 5:
            this.CapturePreviewContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.CapturePreviewScaleTransform = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 7:
            this.CaptureCropVisualOverlay = ((System.Windows.Controls.Canvas)(target));
            return;
            case 8:
            this.CaptureCropRectangle = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 9:
            this.CaptureCropOverlay = ((System.Windows.Controls.Canvas)(target));
            
            #line 98 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CaptureCropOverlay.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCaptureCropMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 99 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CaptureCropOverlay.MouseMove += new System.Windows.Input.MouseEventHandler(this.OnCaptureCropMouseMove);
            
            #line default
            #line hidden
            
            #line 100 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CaptureCropOverlay.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.OnCaptureCropMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 101 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CaptureCropOverlay.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCapturePanMouseMiddleButtonDown);
            
            #line default
            #line hidden
            
            #line 102 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CaptureCropOverlay.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.OnCapturePanMouseMiddleButtonUp);
            
            #line default
            #line hidden
            
            #line 103 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CaptureCropOverlay.MouseLeave += new System.Windows.Input.MouseEventHandler(this.OnCaptureCropMouseLeave);
            
            #line default
            #line hidden
            
            #line 104 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CaptureCropOverlay.MouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.OnCapturePreviewMouseWheel);
            
            #line default
            #line hidden
            return;
            case 10:
            this.CaptureSelectionRectangle = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 11:
            this.CaptureCoordinateBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.CaptureCoordinateText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.CaptureRoiBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.CaptureRoiText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.PreviewSurface = ((System.Windows.Controls.Grid)(target));
            
            #line 260 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.PreviewSurface.SizeChanged += new System.Windows.SizeChangedEventHandler(this.OnPreviewSurfaceSizeChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            this.PreviewPanContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 17:
            this.PreviewTranslateTransform = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 18:
            this.PreviewContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 19:
            this.PreviewScaleTransform = ((System.Windows.Media.ScaleTransform)(target));
            return;
            case 20:
            this.CropVisualOverlay = ((System.Windows.Controls.Canvas)(target));
            return;
            case 21:
            this.CropRectangle = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 22:
            this.CropOverlay = ((System.Windows.Controls.Canvas)(target));
            
            #line 287 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CropOverlay.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCropMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 288 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CropOverlay.MouseMove += new System.Windows.Input.MouseEventHandler(this.OnCropMouseMove);
            
            #line default
            #line hidden
            
            #line 289 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CropOverlay.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.OnCropMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 290 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CropOverlay.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.OnPanMouseMiddleButtonDown);
            
            #line default
            #line hidden
            
            #line 291 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CropOverlay.MouseUp += new System.Windows.Input.MouseButtonEventHandler(this.OnPanMouseMiddleButtonUp);
            
            #line default
            #line hidden
            
            #line 292 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CropOverlay.MouseLeave += new System.Windows.Input.MouseEventHandler(this.OnCropMouseLeave);
            
            #line default
            #line hidden
            
            #line 293 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.CropOverlay.MouseWheel += new System.Windows.Input.MouseWheelEventHandler(this.OnPreviewMouseWheel);
            
            #line default
            #line hidden
            return;
            case 23:
            this.SelectionRectangle = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 24:
            this.ImageMatchBestRectangle = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 25:
            this.PreviewCoordinateBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 26:
            this.PreviewCoordinateText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.PreviewRoiBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 28:
            this.PreviewRoiText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 29:
            this.PreviewMatchBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 30:
            this.PreviewMatchText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            this.EmptyPreview = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 32:
            this.PipelineRoiSurface = ((System.Windows.Controls.Grid)(target));
            
            #line 977 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.PipelineRoiSurface.SizeChanged += new System.Windows.SizeChangedEventHandler(this.OnPipelineRoiSurfaceSizeChanged);
            
            #line default
            #line hidden
            return;
            case 33:
            this.PipelineRoiOverlay = ((System.Windows.Controls.Canvas)(target));
            
            #line 983 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.PipelineRoiOverlay.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnPipelineRoiMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 984 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.PipelineRoiOverlay.MouseMove += new System.Windows.Input.MouseEventHandler(this.OnPipelineRoiMouseMove);
            
            #line default
            #line hidden
            
            #line 985 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.PipelineRoiOverlay.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.OnPipelineRoiMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 986 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\DeveloperToolsView.xaml"
            this.PipelineRoiOverlay.MouseLeave += new System.Windows.Input.MouseEventHandler(this.OnPipelineRoiMouseLeave);
            
            #line default
            #line hidden
            return;
            case 34:
            this.PipelineSelectionRectangle = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 35:
            this.PipelineRoiRectangle = ((System.Windows.Shapes.Rectangle)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

