#pragma checksum "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B6B87EECEDE30A63E37770E901856042508EB75A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using UmamusumeWpfGui.Converters;
using UmamusumeWpfGui.Models;
using UmamusumeWpfGui.ViewModels;
using UmamusumeWpfGui.Views;
using Wpf.Ui;
using Wpf.Ui.Controls;
using Wpf.Ui.Converters;
using Wpf.Ui.Markup;


namespace UmamusumeWpfGui.Views {
    
    
    /// <summary>
    /// GrassView
    /// </summary>
    public partial class GrassView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 108 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid HachimiWorkspace;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox TaskQueueListBox;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas TaskQueueOverlay;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TaskDropIndicator;
        
        #line default
        #line hidden
        
        
        #line 172 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TaskDragPreview;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer HachimiTaskLogScrollViewer;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/UmamusumeAss;V0.2.2.0;component/views/grassview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\GrassView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.HachimiWorkspace = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.TaskQueueListBox = ((System.Windows.Controls.ListBox)(target));
            return;
            case 3:
            this.TaskQueueOverlay = ((System.Windows.Controls.Canvas)(target));
            return;
            case 4:
            this.TaskDropIndicator = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.TaskDragPreview = ((System.Windows.Controls.Border)(target));
            return;
            case 6:
            this.HachimiTaskLogScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

