#pragma checksum "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9CDDCABFFBC206EE87B22ED7DA8816F4BCB88A13"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Stylet.Xaml;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using UmamusumeWpfGui.Converters;
using UmamusumeWpfGui.Views;
using Wpf.Ui;
using Wpf.Ui.Controls;
using Wpf.Ui.Converters;
using Wpf.Ui.Markup;


namespace UmamusumeWpfGui.Views {
    
    
    /// <summary>
    /// RootView
    /// </summary>
    public partial class RootView : Wpf.Ui.Controls.FluentWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 88 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Wpf.Ui.Controls.NavigationView RootNavigation;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas NavigationIndicatorCanvas;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border NavigationSelectionIndicator;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/UmamusumeAss;V0.2.2.0;component/views/rootview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.RootNavigation = ((Wpf.Ui.Controls.NavigationView)(target));
            
            #line 98 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            this.RootNavigation.SelectionChanged += new Wpf.Ui.Controls.TypedEventHandler<Wpf.Ui.Controls.NavigationView, System.Windows.RoutedEventArgs>(this.OnRootNavigationSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 109 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnNavigationItemPreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 110 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnNavigationItemClick);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 117 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnNavigationItemPreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 118 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnNavigationItemClick);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 125 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnNavigationItemPreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 126 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnNavigationItemClick);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 133 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnNavigationItemPreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 134 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnNavigationItemClick);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 144 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnNavigationItemPreviewMouseDown);
            
            #line default
            #line hidden
            
            #line 145 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\RootView.xaml"
            ((Wpf.Ui.Controls.NavigationViewItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnNavigationItemClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.NavigationIndicatorCanvas = ((System.Windows.Controls.Canvas)(target));
            return;
            case 8:
            this.NavigationSelectionIndicator = ((System.Windows.Controls.Border)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

