#pragma checksum "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0B3A95AA275335DF661B86E2EEF7CD72E88CBFB1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using UmamusumeWpfGui.Converters;
using Wpf.Ui;
using Wpf.Ui.Controls;
using Wpf.Ui.Converters;
using Wpf.Ui.Markup;


namespace UmamusumeWpfGui.Views {
    
    
    /// <summary>
    /// SettingsView
    /// </summary>
    public partial class SettingsView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 258 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl SettingsTabs;
        
        #line default
        #line hidden
        
        
        #line 266 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ConnectionSettingCardGroup;
        
        #line default
        #line hidden
        
        
        #line 485 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel DeviceSettingCardGroup;
        
        #line default
        #line hidden
        
        
        #line 539 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ControlReadinessSettingCardGroup;
        
        #line default
        #line hidden
        
        
        #line 573 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel LanguageSettingCardGroup;
        
        #line default
        #line hidden
        
        
        #line 607 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel SystemSettingCardGroup;
        
        #line default
        #line hidden
        
        
        #line 632 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel UpdatesSettingCardGroup;
        
        #line default
        #line hidden
        
        
        #line 684 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel HachimiSettingCardGroup;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/UmamusumeAss;V0.2.2.0;component/views/settingsview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SettingsTabs = ((System.Windows.Controls.TabControl)(target));
            return;
            case 2:
            this.ConnectionSettingCardGroup = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 3:
            
            #line 337 "..\..\..\..\..\..\src\UmamusumeWpfGui\Views\SettingsView.xaml"
            ((Wpf.Ui.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnBrowseAdbPath);
            
            #line default
            #line hidden
            return;
            case 4:
            this.DeviceSettingCardGroup = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 5:
            this.ControlReadinessSettingCardGroup = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.LanguageSettingCardGroup = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 7:
            this.SystemSettingCardGroup = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 8:
            this.UpdatesSettingCardGroup = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 9:
            this.HachimiSettingCardGroup = ((System.Windows.Controls.StackPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

